### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by robot-army** [dlharmon/pyopenems#2]
Hi! Super excited to try this out after hearing about it from the talk at KiCON. I'm trying to install on a fresh copy of debian 10, but:

1) git submodule pull failed, git submodule update --recursive seemed to do something (but I'm not sure if it was the right thing)
2) openems/share/python doesn't exist, same for CSXCAD, only matlab exists, so it doesn't look like it did the trick. 

Thanks for all your efforts on this, I'm super excited to try it out!

**Comment by robot-army** [comment]
Nevermind, I'm a derp, I was looking in the wrong folder!

**Comment by robot-army** [comment]
Ehhhh, maybe not... now getting "No module named 'Cython'"

**Comment by robot-army** [comment]
sudo apt install python3-pip
pip3 install Cython

**Comment by robot-army** [comment]
Now throwing 'no module named cython' after the sudo bit...

**Comment by dlharmon** [comment]
try

```sudo apt install cython3```

instead of using pip to install it

**Comment by robot-army** [comment]
sudo pip3 install Cython seemed to do it

try "cd CSXCAD/python; python3 setup.py build_ext -I$OPENEMS/include -L$OPENEMS/lib -R$OPENEMS/lib; sudo python3 setup.py install; cd ../.." again, gets a bit further, now:

"fatal error: CSXCAD/ParameterObjects.h no such file or directory"

It seems that's in CSXCAD/src/...

**Comment by robot-army** [comment]
Oh cool, thanks! Sorry for the stream of consciousness here, I'm sure it'll all come out in the wash eventually...I'll keep plugging along

**Comment by robot-army** [comment]
Right... trying again: 
```
robot-army@debian:~/openEMS-Project$ cd CSXCAD/python; python3 setup.py build_ext -I$OPENEMS/include -L$OPENEMS/lib -R$OPENEMS/lib; sudo python3 setup.py install; cd ../..
running build_ext
building 'CSXCAD.CSPrimitives' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/include -I/usr/include/python3.7m -c CSXCAD/CSPrimitives.cpp -o build/temp.linux-x86_64-3.7/CSXCAD/CSPrimitives.o
CSXCAD/CSPrimitives.cpp:633:10: fatal error: CSXCAD/ParameterObjects.h: No such file or directory
 #include "CSXCAD/ParameterObjects.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
